### PR TITLE
Fix arg passing from js

### LINKED ISSUE #54: Azure CLI command parsing bugs (MacOS)
macOS 15.4

zsh 5.9

[`@azure/mcp@0.0.10`](https://www.npmjs.com/package/@azure/mcp/v/0.0.10)

https://github.com/Azure/azure-mcp/blob/main/docs/azmcp-commands.md#azure-cli-extension-operations

# CLI issues:

---

fails:
```sh
% azmcp extension az --command 'group list'
Unrecognized command or argument 'list'.
```

works:
Seems to require manual escaping
```sh
% azmcp extension az --command 'group\ list'
{
  "status": 200,
  "message": "Success",
  ... 
}
```

---

fails:
```sh
% azmcp extension az --command 'ad user list --filter "startswith(displayName,'"'John'"')"'
Unrecognized command or argument 'user'.
Unrecognized command or argument 'list'.
Unrecognized command or argument '--filter'.
Unrecognized command or argument 'startswith(displayName,'John')'.
```

works:
Again, manual escaping
```sh
% azmcp extension az --command 'ad\ user\ list\ --filter\ "startswith(displayName,'"'John'"')"'
{
  "status": 200,
  "message": "Success",
  ...
}
```

fails:
```sh
% azmcp extension az --command 'ad\ user\ list\ --filter\ "startswith(displayName,'"'John Doe'"')"'
{
  "status": 500,
  "message": "ERROR: unrecognized arguments: Doe')\n\nExamples from AI knowledge base:\naz ad user list\nList Azure Active Directory users. (autogenerated)\n\naz ad user list --upn {upn}\nList Azure Active Directory users. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/ad/user#az_ad_user_list\nRead more about the command in reference docs",
  ...
}
```

fails:
Haven't figured out the way the escape this command for `azmcp` to not fail yet.
```sh
% azmcp extension az --command 'ad\ user\ list\ --filter\ "startswith(displayName,'"'John\ Doe'"')"'
{
  "status": 500,
  "message": "ERROR: unrecognized arguments: Doe')\n\nExamples from AI knowledge base:\naz ad user list\nList Azure Active Directory users. (autogenerated)\n\naz ad user list --upn {upn}\nList Azure Active Directory users. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/ad/user#az_ad_user_list\nRead more about the command in reference docs",
  ...
}
```

# VS Code Copilot

works:
Image

```json
{
  "command": "group list",
  "auth-method": "credential"
}

[{...},{...},{...}]
```

fails:
Image

Doesn't get the argument passed to `--filter`. Retry continues to fail.
```json
{
  "command": "ad user list --filter \"startswith(displayName,'John Doe')\"",
  "auth-method": "credential"
}

{
  "ExitCode": 2,
  "Error": "ERROR: argument --filter: expected one argument\n\nExamples from AI knowledge base:\naz ad user list\nList Azure Active Directory users. (autogenerated)\n\naz ad user list --upn {upn}\nList Azure Active Directory users. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/ad/user#az_ad_user_list\nRead more about the command in reference docs",
  "Command": "/opt/homebrew/bin/az ad user list --filter "
}
```

Formatted error:
```
ERROR: argument --filter: expected one argument

Examples from AI knowledge base:
az ad user list
List Azure Active Directory users. (autogenerated)

az ad user list --upn {upn}
List Azure Active Directory users. (autogenerated)

https://docs.microsoft.com/en-US/cli/azure/ad/user#az_ad_user_list
Read more about the command in reference docs
```

### PR DESCRIPTION
**Pull request by hallipr**
## What does this PR do?
Fixes arg parsing/passing between javascript and the cli

## GitHub issue number?
fixes #54

## Checklist before merging
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-mcp/blob/main/CONTRIBUTING.md) on pull request process, code style, and testing.**
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message.  This means that previously merged commits do not appear in the history of the PR.  For more information on cleaning up the commits in your PR,  [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] If it's a core feature, I have added thorough tests.
- [x] If it's a noteworthy bug fix or new feature, I have added an entry in CHANGELOG.md with a link back to the PR or issue
- [x] Have a team member run [live tests](https://github.com/Azure/azure-mcp/blob/main/CONTRIBUTING.md#live-tests):
   - [x] Team Member: Inspect PR for security issues before queueing a test run
   - [x] Team Member: Add this comment to the pr `/azp run azure - mcp` to start the run

### CODE REVIEW

File: src/Program.cs [hunk 1]
```diff
@@ -74,4 +75,25 @@ internal static void ConfigureServices(IServiceCollection services)
...
+    internal static void LogDebugArgs(string[] args)
+    {
+        string debug = Environment.GetEnvironmentVariable("DEBUG") ?? string.Empty;
+
+        bool isDebugEnabled =
+            debug.Equals("true", StringComparison.OrdinalIgnoreCase) ||
+            debug.Contains("azure-mcp", StringComparison.OrdinalIgnoreCase) ||
+            debug == "*";
+
+        //if (isDebugEnabled)
```
Comment (jongio) [inline src/Program.cs:88]: Does this compile?

Comment (hallipr) [reply src/Program.cs:88]: it does

Comment (hallipr) [reply src/Program.cs:88]: You worried about whitespace?

Comment (joshfree) [reply src/Program.cs:88]: nit:  do you mind yanking the commented-out if-check and removing the L89 / L97 scope

File: eng/scripts/Build-Local.ps1 [hunk 2]
```diff
@@ -3,26 +3,31 @@
...
-    [switch] $UsePaths,
     [switch] $AllPlatforms,
-    [switch] $VerifyNpx
+    [switch] $VerifyNpx,
+    [string] $NpxArgs = 'tools list'
 )
 
-$RepoRoot = (Resolve-Path "$PSScriptRoot/../..").Path.Replace('\', '/')
+. "$PSScriptRoot/../common/scripts/common.ps1"
+$root = $RepoRoot.Path.Replace('\', '/')
```
Comment (joshfree) [inline eng/scripts/Build-Local.ps1:15]: just a style comment, but I'd probably put this in a getRoot helper

**Review by joshfree — APPROVED** [review]

**Review by conniey — APPROVED** [review]
LGTM. Needs a CHANGELOG update. :)

**Comment by joshfree** [comment]
assigning to @hallipr since this just needs to be rebased, re-reviewed, and merged.   Waiting on hallipr for next step.

File: eng/scripts/Build-Local.ps1 (hunk 2 above)
Comment (hallipr) [reply eng/scripts/Build-Local.ps1:15]: $RepoRoot is already a helper from `eng/common/scripts/common.ps1`.
I'm just flipping the slash direction to avoid Join-Path everywhere

Comment (hallipr) [reply eng/scripts/Build-Local.ps1]: I've pulled out all of the changes other than the arg passing fix in JS

**Review by JonathanCrd — APPROVED** [review]
🚀
