### PR TITLE
Fix code conventions

### LINKED ISSUE #180: Update code for coding conventions.
e.g.

private const string CACHE_GROUP = "subscription";

We should use something like

https://github.com/dotnet/runtime/blob/fdbe38ce16671ae356e2bad21479e38b61d03340/src/libraries/System.Private.CoreLib/src/System/Char.cs#L48

private const byte IsWhiteSpaceFlag = 0x80;

### PR DESCRIPTION
**Pull request by xiangyan99**
## What does this PR do?

To close #180

## GitHub issue number?

#180

## Checklist before merging
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-mcp/blob/main/CONTRIBUTING.md) on pull request process, code style, and testing.**
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message.  This means that previously merged commits do not appear in the history of the PR.  For more information on cleaning up the commits in your PR,  [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] If it's a core feature, I have added thorough tests.
- [ ] If it's a noteworthy bug fix or new feature, I have added an entry in CHANGELOG.md with a link back to the PR or issue
- [ ] Have a team member run [live tests](https://github.com/Azure/azure-mcp/blob/main/CONTRIBUTING.md#live-tests):
   - [ ] Team Member: Inspect PR for security issues before queueing a test run
   - [ ] Team Member: Add this comment to the pr `/azp run azure - mcp` to start the run

### CODE REVIEW

File: src/Commands/AppConfig/Account/AccountListCommand.cs [hunk 1]
```diff
@@ -11,7 +11,7 @@ namespace AzureMcp.Commands.AppConfig.Account;
```
Comment (jongio) [inline src/Commands/AppConfig/Account/AccountListCommand.cs:11]: Are these conventions coming from .NET sdk repo?  If not, let's take the time to snap to that.

I'm wondering why some private are _camel and some are Pascal.  

new-command.md will also need to be updated.

File: src/Commands/Storage/Blob/Container/ContainerDetailsCommand.cs [hunk 2]
```diff
@@ -23,9 +23,9 @@ public sealed class ContainerDetailsCommand(ILogger<ContainerDetailsCommand> log
         Requires {OptionDefinitions.Storage.AccountName} and {OptionDefinitions.Storage.ContainerName}.
         """;
 
-    public override string Title => _commandTitle;
+    public override string Title => CommandTitle;
 
-    [McpServerTool(Destructive = false, ReadOnly = true)]
+    [McpServerTool(Destructive = false, ReadOnly = true, Title = CommandTitle)]
```
Comment (christothes) [inline src/Commands/Storage/Blob/Container/ContainerDetailsCommand.cs:28]: Let's add a test that ensures that all ExecuteAsync commands decorated with the `McPServerTool` attribute include a Title property.

Comment (xiangyan99) [reply src/Commands/Storage/Blob/Container/ContainerDetailsCommand.cs:28]: Added

File: src/Commands/AppConfig/Account/AccountListCommand.cs (hunk 1 above)
Comment (conniey) [reply src/Commands/AppConfig/Account/AccountListCommand.cs:11]: These naming changes conflict with the ones in our editorconfig.
https://github.com/Azure/azure-mcp/blob/main/.editorconfig#L54-L57

We execute dotnet format before pushing any changes to GitHub: https://github.com/Azure/azure-mcp/blob/main/eng/scripts/git-hooks/pre-push#L15

dotnet format uses the rules in .editorconfig.

File: src/Commands/CommandFactory.cs [hunk 3]
```diff
@@ -20,7 +20,7 @@ public class CommandFactory
     private readonly CommandGroup _rootGroup;
     private readonly ModelsJsonContext _srcGenWithOptions;
 
-    internal static readonly char Separator = '-';
+    internal static readonly char s_separator = '-';
```
Comment (conniey) [inline src/Commands/CommandFactory.cs:23]: Can we make this const instead? I don't think it needs to be static.

File: tests/Commands/Server/McpServerToolAttributeTests.cs [hunk 4]
```diff
@@ -0,0 +1,194 @@
...
+using ModelContextProtocol.Server;
+using NSubstitute;
+using Xunit;
+
+namespace AzureMcp.Tests.Commands.Server;
+
+public class McpServerToolAttributeTests
+{
+    [Fact]
+    public void AllExecuteAsyncMethodsWithMcpServerToolAttribute_ShouldHaveTitleProperty()
```
Comment (christothes) [inline tests/Commands/Server/McpServerToolAttributeTests.cs:17]: nit - let's combine these attribute tests into a single test that checks for non-null, non-empty, and meaningful.

**Review by conniey — APPROVED** [review]
